### ISSUE TITLE
ISSUE, table name specified more than once

### ISSUE THREAD

**Issue by raza** [binarylogic/searchlogic#19]
ERROR MESSAGE: "ActiveRecord::StatementInvalid (PGError: ERROR:  table name "tender_flags" specified more than once"

I am using a join with one table and as I use order by with that table it gives this error
Also any association based sorting by default use INNER JOIN but in my scenario I require LEFT JOIN any suggestion for getting through that issue. thanks.

**Comment by raza** [comment]
Details;
User.ascend_by_role_is_admin
in that case the query is;
User Load (1.5ms) SELECT "users".\* FROM "users" INNER JOIN "roles" ON roles.user_id = users.id ORDER BY roles.is_admin ASC

whereas I need LEFT JOIN in the query for getting all records but order by is_admin field.

**Comment by ghost** [comment]
I have this same problem in my application. There is no easy way around this. Your best bet is to write your own order condition that uses the same join so that AR will remove the duplicates. The other option is to give your left outer joins aliases like "optional_roles". This is what I've been doing in my apps. This really isn't an issue with SL directly, its more of an issue with just combining named scopes. If you want to modify the join that SL creates, you are better off just creating the named scope yourself and adding the join that you want.

Thanks.
